from enum import Enum


class InstrumentIssueName(str, Enum):
    APPROACHING_MAX_POSITION_SIZE = "APPROACHING_MAX_POSITION_SIZE"
    COMPLEX_INSTRUMENT_APP_TEST_REQUIRED = "COMPLEX_INSTRUMENT_APP_TEST_REQUIRED"
    DELISTED = "DELISTED"
    MAX_POSITION_SIZE_REACHED = "MAX_POSITION_SIZE_REACHED"
    NO_LONGER_TRADABLE = "NO_LONGER_TRADABLE"
    SUSPENDED = "SUSPENDED"

    def __str__(self) -> str:
        return str(self.value)
